# Generated by Django 5.2.8 on 2025-11-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=200, verbose_name='Название курса')),
                ('student_name', models.CharField(max_length=100, verbose_name='Имя ученика')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Заказ выполнен')),
            ],
            options={
                'verbose_name': 'Заказ курса',
                'verbose_name_plural': 'Заказы курсов',
                'ordering': ['-order_date'],
            },
        ),
    ]
