# Generated by Django 5.2.8 on 2025-12-02 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(verbose_name='ID курса')),
                ('course_title', models.CharField(max_length=200, verbose_name='Название курса')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('completed', 'Завершенный'), ('cancelled', 'Отмененный')], default='active', max_length=20, verbose_name='Статус')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('course_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to='homepage.courseorder', verbose_name='Заказ курса')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Курс пользователя',
                'verbose_name_plural': 'Курсы пользователей',
                'unique_together': {('user', 'course_order')},
            },
        ),
    ]
